### ISSUE TITLE
Apply a custom style to a group of common widgets

### ISSUE THREAD

**Issue by Mahmoood** [Amejia481/Associate-Android-Developer-Certification#4]
In this section 'Widget' means the common control (Button, TextView, .....) not the widget screen that appears on the device home screen.
So the mentioned references in this context is not correct.

**Comment by Amejia481** [comment]
Thanks for noticing it, you're right, we have to fix it!
Do you want to collaborate on this improvements? 
Or do you have any resources relevant to this section?

**Comment by PonnamKarthik** [comment]
repo is open to pull requests

**Comment by Mahmoood** [comment]
I have created a pull request with the fix.
