### ISSUE TITLE
They update EXAM CONTENT 

### ISSUE THREAD

**Issue by MohammadLaif** [Amejia481/Associate-Android-Developer-Certification#8]
They update EXAM CONTENT. Adding new topics such as Room, DAO, LiveData, Paging Library.
https://developers.google.com/training/certification/associate-android-developer/#exam-content

**Comment by Amejia481** [comment]
Thank you so much for the update!

Do you have any related materials for updating the project?

**Comment by MohammadLaif** [comment]
Not yet, I was searching.

**Comment by Amejia481** [comment]
:+1:

**Comment by ShrutiSoni1991** [comment]
I am a beginner, should I attempt and any guidance for beginner who wants to attempt the certification.?

**Comment by KelvnPere** [comment]
Yes i have related materials for the Updated Projects, including  Constraint Layout, and Room Persistence Library

**Comment by Amejia481** [comment]
@Pheonix73  you are welcome to submit a pull request! 👍

**Comment by ShrutiSoni1991** [comment]
@Pheonix73 Thanks For materials.

**Comment by KelvnPere** [comment]
Thanks  @Amejia481 already on it

**Comment by KelvnPere** [comment]
@Amejia481 Just Submitted a pull request

**Comment by Amejia481** [comment]
Thanks @Pheonix73 I'll take look!
